import React from "react";
import { Showcase } from "../../components/Showcase/Showcase";

export const Liquids = () => {
  const mockItems = [
    {
      id: 1,
      title: "АНАРХИЯ V2 HARD",
      description: "",
      taste: "Зеленое Яблоко🍏",
      volume: "30ml",
      nicotine: "20mg HARD (50mg)",
      price: "350",
      image: "https://placehold.co/600x360",
    },
    {
      id: 2,
      title: "АНАРХИЯ V2 HARD",
      description: "",
      taste: "Киви Драгонфрут🥝",
      volume: "30ml",
      nicotine: "20mg HARD (50mg)",
      price: "350",
      image: "https://placehold.co/600x360",
    },
    {
      id: 3,
      title: "АНАРХИЯ V2 HARD",
      description: "",
      taste: "Клюква Брусника🫐🍒",
      volume: "30ml",
      nicotine: "20mg HARD (50mg)",
      price: "350",
      image: "https://placehold.co/600x360",
    },
    {
      id: 4,
      title: "АНАРХИЯ V2 HARD",
      description: "",
      taste: "Малиновый Лимонад🍓🥤",
      volume: "30ml",
      nicotine: "20mg HARD (50mg)",
      price: "350",
      image: "https://placehold.co/600x360",
    },
    {
      id: 5,
      title: "Hotspot X Podonki Resonance EXTRA HARD",
      description: "",
      taste: "Газировка тархун🥤",
      volume: "30ml",
      nicotine: "20mg Hard",
      price: "360",
      image: "https://placehold.co/600x360",
    },
    {
      id: 6,
      title: "Hotspot X Podonki Resonance EXTRA HARD",
      description: "",
      taste: "Освежающий Ананас🍍🧊",
      volume: "30ml",
      nicotine: "20mg Hard",
      price: "360",
      image: "https://placehold.co/600x360",
    },
    {
      id: 7,
      title: "RICK and MORTY BAD ACID EXTRA HARD",
      description: "",
      taste: "Ананасовый леденец🍍🍭",
      volume: "30ml",
      nicotine: "20mg HARD (40-50mg)",
      price: "360",
      image: "https://placehold.co/600x360",
    },
    {
      id: 8,
      title: "RICK and MORTY BAD ACID EXTRA HARD",
      description: "",
      taste: "Киви лайм🥝🍋‍🟩",
      volume: "30ml",
      nicotine: "20mg HARD (40-50mg)",
      price: "360",
      image: "https://placehold.co/600x360",
    },
    {
      id: 9,
      title: "RICK and MORTY BAD ACID EXTRA HARD",
      description: "",
      taste: "Мармеладные червячки голубика малина🫐🍓",
      volume: "30ml",
      nicotine: "20mg HARD (40-50mg)",
      price: "360",
      image: "https://placehold.co/600x360",
    },
    {
      id: 10,
      title: "RICK and MORTY BAD ACID EXTRA HARD",
      description: "",
      taste: "Фруктовый Скитлс🍏🍎",
      volume: "30ml",
      nicotine: "20mg HARD (40-50mg)",
      price: "360",
      image: "https://placehold.co/600x360",
    },
    {
      id: 11,
      title: "ЗЛАЯ МОНАШКА",
      description: "",
      taste: "Энергетик вишня лед⚡️🍒",
      volume: "30ml",
      nicotine: "70mg HARD",
      price: "360",
      image: "https://placehold.co/600x360",
    },
    {
      id: 12,
      title: "ЗЛАЯ МОНАШКА",
      description: "",
      taste: "Апельсин с кислой малиной🍊",
      volume: "30ml",
      nicotine: "70mg HARD",
      price: "360",
      image: "https://placehold.co/600x360",
    },
    {
      id: 13,
      title: "ЗЛАЯ МОНАШКА",
      description: "",
      taste: "Вишня черника🍒🫐",
      volume: "30ml",
      nicotine: "70mg HARD",
      price: "360",
      image: "https://placehold.co/600x360",
    },
    {
      id: 14,
      title: "ЗЛАЯ МОНАШКА",
      description: "",
      taste: "Жвачка земляника💕🍓",
      volume: "30ml",
      nicotine: "70mg HARD",
      price: "360",
      image: "https://placehold.co/600x360",
    },
  ];
  return (
    <div>
      <Showcase title="Жидкости" dataUrl={mockItems} type="liquids" />
    </div>
  );
};
